app:
  name: "{{ cookiecutter.project_slug }}"
  language: python

build:
  builder: cnb
  cnb:
    builder: paketobuildpacks/builder-jammy-base

image:
  registry: ghcr.io
  namespace: "{{ cookiecutter.registry_namespace }}"
  name: "{{ cookiecutter.project_slug }}"

stages:
  lint:
    enabled: true
    commands:
      - language: python
        cmd: ruff check .
  test:
    enabled: true
    commands:
      - language: python
        cmd: pytest
