app:
  name: "{{ cookiecutter.project_slug }}"
  language: go

build:
  builder: cnb
  cnb:
    builder: paketobuildpacks/builder-jammy-base

image:
  registry: ghcr.io
  namespace: "{{ cookiecutter.registry_namespace }}"
  name: "{{ cookiecutter.project_slug }}"

stages:
  lint:
    enabled: true
    commands:
      - language: go
        cmd: go vet ./...
  test:
    enabled: true
    commands:
      - language: go
        cmd: go test ./...
