FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod .
COPY src/ src/
RUN go build -o server ./src

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/server .
ENV PORT=8080
EXPOSE 8080
CMD ["./server"]
